# Generated by Django 4.0.6 on 2025-05-14 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=64)),
                ('asset_manufacturer_name', models.CharField(max_length=255)),
                ('asset_name_model', models.CharField(max_length=255)),
                ('asset_serial_number', models.CharField(max_length=255)),
                ('asset_deployment', models.CharField(max_length=100)),
                ('asset_classification', models.CharField(max_length=100)),
                ('asset_description', models.TextField()),
                ('asset_commisioning_date', models.DateField(blank=True, null=True)),
                ('asset_certifications', models.JSONField(blank=True, null=True)),
                ('asset_release_year', models.IntegerField(blank=True, null=True)),
                ('flexibility_type', models.CharField(max_length=100)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.JSONField()),
                ('weight', models.FloatField()),
                ('form_factor', models.CharField(max_length=100)),
                ('main_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.mainasset')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalSafetySpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_rating', models.CharField(max_length=50)),
                ('storage_temperature', models.JSONField()),
                ('operating_temperature_range', models.JSONField()),
                ('relative_humidity_range', models.JSONField()),
                ('main_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.mainasset')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalSpecsUpward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_configuration', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('voltage_nominal', models.IntegerField()),
                ('voltage_regulation', models.FloatField()),
                ('voltage_range', models.JSONField()),
                ('current_output_nominal', models.FloatField()),
                ('output_current_max', models.JSONField()),
                ('power_output_nominal', models.JSONField()),
                ('power_output_max', models.JSONField()),
                ('standby_power_consumption', models.FloatField()),
                ('power_factor', models.FloatField()),
                ('main_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.mainasset')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalSpecsDownward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_configuration', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('voltage_nominal', models.IntegerField()),
                ('voltage_tolerance', models.FloatField()),
                ('current_nominal', models.FloatField()),
                ('current_min', models.FloatField()),
                ('current_max', models.FloatField()),
                ('inrush_current_max', models.FloatField()),
                ('power_consumption_nominal', models.FloatField()),
                ('power_consumption_max', models.FloatField()),
                ('standby_power_consumption', models.FloatField()),
                ('energy_efficiency_class', models.CharField(max_length=10)),
                ('main_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.mainasset')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalSpecsBESS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=100)),
                ('cell_type', models.CharField(max_length=100)),
                ('voltage_nominal', models.FloatField()),
                ('voltage_range', models.JSONField()),
                ('capacity', models.JSONField()),
                ('maximum_charge_current', models.FloatField()),
                ('maximum_discharge_current', models.FloatField()),
                ('cycle_life', models.JSONField()),
                ('energy_rating_nominal', models.FloatField()),
                ('c_rate', models.CharField(max_length=50)),
                ('round_trip_efficiency', models.FloatField()),
                ('battery_management_system', models.JSONField()),
                ('degradation_rate', models.FloatField()),
                ('main_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.mainasset')),
            ],
        ),
        migrations.CreateModel(
            name='DataAcquisitionAndControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.JSONField()),
                ('communication_protocol', models.JSONField()),
                ('data_acquisition_actuation', models.JSONField()),
                ('data_acquisition_attributes', models.JSONField()),
                ('control_actuation', models.JSONField()),
                ('regulation_type', models.CharField(max_length=100)),
                ('regulation_response_time_upward', models.JSONField()),
                ('regulation_response_time_downward', models.JSONField()),
                ('maximum_upward_regulation', models.JSONField()),
                ('maximum_downward_regulation', models.JSONField()),
                ('minimum_regulation_step', models.JSONField()),
                ('main_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.mainasset')),
            ],
        ),
    ]
