# Generated by Django 5.2.1 on 2025-05-27 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CellType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.JSONField()),
                ("specs", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.JSONField()),
                ("specs", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_environment", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DevicesAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Flexibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
                ("specs", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Units",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("symbol", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ContentContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("END_USER", "End-User / Asset-Owner"),
                            ("MANUFACTURER", "Manufacturer / Economic Operator"),
                            ("INDEPENDENT", "Independent Content Contributor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "eori_number",
                    models.CharField(
                        blank=True,
                        help_text="Your EU EORI number, e.g. GB123456789000",
                        max_length=30,
                    ),
                ),
                ("relation", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opentunity_did", models.TextField(blank=True, null=True)),
                ("record_insertion_date", models.DateTimeField(auto_now_add=True)),
                ("gtin", models.CharField(blank=True, max_length=14, null=True)),
                ("model_name", models.TextField()),
                ("batch_name", models.TextField(blank=True, null=True)),
                (
                    "serial_number",
                    models.TextField(
                        blank=True, null=True, verbose_name="Serial Number"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("commissioning_date", models.DateTimeField(blank=True, null=True)),
                (
                    "compliance_checklist",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="List of Applicable Directives, Regulations, and Standards",
                    ),
                ),
                ("release_year", models.IntegerField(blank=True, null=True)),
                (
                    "dacq_actuation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Data Acquisition Actuation"
                    ),
                ),
                (
                    "dacq_attributes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Monitored Attributes"
                    ),
                ),
                (
                    "control_actuation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Control Actuation"
                    ),
                ),
                ("regulation_response_time_upward", models.FloatField()),
                ("regulation_response_time_downward", models.FloatField()),
                ("regulation_response_time_accuracy", models.JSONField()),
                ("maximum_upward_regulation", models.JSONField()),
                ("maximum_downward_regulation", models.JSONField()),
                ("minimum_regulation_step", models.JSONField()),
                ("ip_rating", models.TextField(blank=True, null=True)),
                ("storage_temperature", models.JSONField(blank=True, null=True)),
                (
                    "operating_temperature_range",
                    models.JSONField(blank=True, null=True),
                ),
                ("relative_humidity_range", models.JSONField(blank=True, null=True)),
                ("dimensions", models.JSONField(blank=True, null=True)),
                ("weight", models.JSONField(blank=True, null=True)),
                ("form_factor", models.TextField(blank=True, null=True)),
                (
                    "classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.classification",
                    ),
                ),
                (
                    "communication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.communication",
                    ),
                ),
                (
                    "communication_protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.communicationprotocol",
                    ),
                ),
                (
                    "record_contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.contentcontributor",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.deployment",
                    ),
                ),
                (
                    "devices_attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.devicesattributes",
                        verbose_name="Available Attributes",
                    ),
                ),
                (
                    "flexibility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.flexibility",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.manufacturer",
                    ),
                ),
                (
                    "regulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.regulation",
                    ),
                ),
                (
                    "regulation_response_time_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="devices.units",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectricalSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_configuration", models.IntegerField()),
                ("frequency", models.IntegerField()),
                ("voltage_nominal", models.IntegerField()),
                ("voltage_tolerance_df", models.FloatField()),
                ("current_nominal_df", models.FloatField()),
                ("current_min_df", models.FloatField()),
                ("current_max_df", models.FloatField()),
                ("inrush_current_max_df", models.FloatField()),
                ("power_consumption_nominal_df", models.FloatField()),
                ("power_consumption_max_df", models.FloatField()),
                ("standby_power_consumption", models.FloatField()),
                ("voltage_regulation_uf", models.FloatField()),
                ("voltage_range_uf", models.JSONField()),
                ("output_current_nominal_uf", models.FloatField()),
                ("output_current_max_uf", models.JSONField()),
                ("power_output_nominal_uf", models.JSONField()),
                ("power_output_max_uf", models.JSONField()),
                ("power_factor", models.FloatField()),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elec_specs",
                        to="devices.asset",
                    ),
                ),
                (
                    "power_consumption_units",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="devices.units"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BESSSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application", models.TextField()),
                ("voltage_nominal", models.FloatField()),
                ("voltage_range", models.JSONField()),
                ("capacity", models.JSONField()),
                ("maximum_charge_current", models.FloatField()),
                ("maximum_discharge_current", models.FloatField()),
                ("cycle_life", models.JSONField()),
                ("energy_rating_nominal", models.FloatField()),
                ("energy_rating_usable", models.FloatField()),
                ("c_rate", models.TextField()),
                ("round_trip_efficiency", models.FloatField()),
                ("battery_management_system", models.JSONField()),
                ("degradation_rate", models.FloatField()),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bess_specs",
                        to="devices.asset",
                    ),
                ),
                (
                    "cell_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.celltype",
                    ),
                ),
                (
                    "energy_rating_nominal_units",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="devices.units",
                    ),
                ),
                (
                    "energy_rating_usable_units",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="devices.units",
                    ),
                ),
            ],
        ),
    ]
