# Generated by Django 4.0.6 on 2025-05-18 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opentunity_did', models.TextField(blank=True, null=True)),
                ('record_insertion_date', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.TextField()),
                ('batch_name', models.TextField(blank=True, null=True)),
                ('serial_number', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('commissioning_date', models.DateTimeField(blank=True, null=True)),
                ('certifications', models.JSONField(blank=True, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('dacq_actuation', models.TextField()),
                ('dacq_attributes', models.TextField()),
                ('control_actuation', models.TextField()),
                ('regulation_response_time_upward', models.FloatField()),
                ('regulation_response_time_downward', models.FloatField()),
                ('regulation_response_time_accuracy', models.JSONField()),
                ('maximum_upward_regulation', models.JSONField()),
                ('maximum_downward_regulation', models.JSONField()),
                ('minimum_regulation_step', models.JSONField()),
                ('ip_rating', models.TextField(blank=True, null=True)),
                ('storage_temperature', models.JSONField(blank=True, null=True)),
                ('operating_temperature_range', models.JSONField(blank=True, null=True)),
                ('relative_humidity_range', models.JSONField(blank=True, null=True)),
                ('dimensions', models.JSONField(blank=True, null=True)),
                ('weight', models.JSONField(blank=True, null=True)),
                ('form_factor', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BESSSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.TextField()),
                ('voltage_nominal', models.FloatField()),
                ('voltage_range', models.JSONField()),
                ('capacity', models.JSONField()),
                ('maximum_charge_current', models.FloatField()),
                ('maximum_discharge_current', models.FloatField()),
                ('cycle_life', models.JSONField()),
                ('energy_rating_nominal', models.FloatField()),
                ('energy_rating_usable', models.FloatField()),
                ('c_rate', models.TextField()),
                ('round_trip_efficiency', models.FloatField()),
                ('battery_management_system', models.JSONField()),
                ('degradation_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.JSONField()),
                ('specs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.JSONField()),
                ('specs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('relation', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_environment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_configuration', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('voltage_nominal', models.IntegerField()),
                ('voltage_tolerance_df', models.FloatField()),
                ('current_nominal_df', models.FloatField()),
                ('current_min_df', models.FloatField()),
                ('current_max_df', models.FloatField()),
                ('inrush_current_max_df', models.FloatField()),
                ('power_consumption_nominal_df', models.FloatField()),
                ('power_consumption_max_df', models.FloatField()),
                ('standby_power_consumption', models.FloatField()),
                ('voltage_regulation_uf', models.FloatField()),
                ('voltage_range_uf', models.JSONField()),
                ('output_current_nominal_uf', models.FloatField()),
                ('output_current_max_uf', models.JSONField()),
                ('power_output_nominal_uf', models.JSONField()),
                ('power_output_max_uf', models.JSONField()),
                ('power_factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Flexibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('specs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('symbol', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='electricalspecsbess',
            name='main_asset',
        ),
        migrations.RemoveField(
            model_name='electricalspecsdownward',
            name='main_asset',
        ),
        migrations.RemoveField(
            model_name='electricalspecsupward',
            name='main_asset',
        ),
        migrations.RemoveField(
            model_name='environmentalsafetyspecs',
            name='main_asset',
        ),
        migrations.RemoveField(
            model_name='mainasset',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='physicalspecs',
            name='main_asset',
        ),
        migrations.DeleteModel(
            name='DataAcquisitionAndControl',
        ),
        migrations.DeleteModel(
            name='ElectricalSpecsBESS',
        ),
        migrations.DeleteModel(
            name='ElectricalSpecsDownward',
        ),
        migrations.DeleteModel(
            name='ElectricalSpecsUpward',
        ),
        migrations.DeleteModel(
            name='EnvironmentalSafetySpecs',
        ),
        migrations.DeleteModel(
            name='MainAsset',
        ),
        migrations.DeleteModel(
            name='PhysicalSpecs',
        ),
        migrations.AddField(
            model_name='electricalspecs',
            name='power_consumption_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='devices.units'),
        ),
        migrations.AddField(
            model_name='bessspecs',
            name='cell_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.celltype'),
        ),
        migrations.AddField(
            model_name='bessspecs',
            name='energy_rating_nominal_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='devices.units'),
        ),
        migrations.AddField(
            model_name='bessspecs',
            name='energy_rating_usable_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='devices.units'),
        ),
        migrations.AddField(
            model_name='asset',
            name='bess_specs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.bessspecs'),
        ),
        migrations.AddField(
            model_name='asset',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.classification'),
        ),
        migrations.AddField(
            model_name='asset',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.communication'),
        ),
        migrations.AddField(
            model_name='asset',
            name='communication_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.communicationprotocol'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.deployment'),
        ),
        migrations.AddField(
            model_name='asset',
            name='electrical_specs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.electricalspecs'),
        ),
        migrations.AddField(
            model_name='asset',
            name='flexibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.flexibility'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.manufacturer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='record_contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.contentcontributor'),
        ),
        migrations.AddField(
            model_name='asset',
            name='regulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.regulation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='regulation_response_time_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='devices.units'),
        ),
    ]
