# Generated by Django 5.2.1 on 2025-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="gtin",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="serial_number",
            field=models.TextField(blank=True, null=True, verbose_name="Serial #"),
        ),
    ]
