# Generated by Django 5.2.1 on 2025-05-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_asset_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="regulation_response_time_downward",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="regulation_response_time_upward",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
