# Generated by Django 5.2.1 on 2025-05-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_asset_gtin_alter_asset_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcontributor",
            name="eori_number",
            field=models.CharField(
                blank=True,
                help_text="Your EU EORI number, e.g. GB123456789000",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="contentcontributor",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="contentcontributor",
            name="gtin_number",
            field=models.CharField(
                blank=True,
                help_text="A GTIN for your resource, e.g. 00012345600012",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contentcontributor",
            name="role",
            field=models.CharField(
                choices=[
                    ("END_USER", "End-User / Asset-Owner"),
                    ("MANUFACTURER", "Manufacturer / Economic Operator"),
                    ("INDEPENDENT", "Independent Content Contributor"),
                ],
                max_length=20,
            ),
        ),
    ]
