# Generated by Django 5.2.1 on 2025-05-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_alter_asset_regulation_response_time_downward_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="regulation_response_time_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="devices.units",
            ),
        ),
    ]
