# Generated by Django 5.2.1 on 2025-05-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_contentcontributor_eori_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentcontributor",
            name="gtin_number",
        ),
    ]
