# Generated by Django 5.2.1 on 2025-05-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_asset_regulation_response_time_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="regulation_response_time_accuracy",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
