# Generated by Django 5.2.1 on 2025-05-28 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_alter_asset_regulation_response_time_accuracy"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoltageRegulationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Voltage Regulation Option",
                "verbose_name_plural": "Voltage Regulation Options",
            },
        ),
        migrations.AlterField(
            model_name="electricalspecs",
            name="voltage_regulation_uf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="devices.voltageregulationoption",
                verbose_name="Voltage regulation",
            ),
        ),
    ]
