# Generated by Django 5.2.1 on 2025-05-28 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_voltageregulationoption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BessApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_name",
                    models.CharField(
                        help_text="Human-readable name of the BESS application",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="bessspecs",
            name="application",
        ),
        migrations.AddField(
            model_name="bessspecs",
            name="bess_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="devices.bessapplication",
                verbose_name="Application",
            ),
        ),
    ]
