# Generated by Django 5.2.1 on 2025-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_bessapplication_remove_bessspecs_application_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="maximum_downward_regulation",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="maximum_upward_regulation",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="minimum_regulation_step",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bessspecs",
            name="battery_management_system",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bessspecs",
            name="capacity",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bessspecs",
            name="cycle_life",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bessspecs",
            name="voltage_range",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="electricalspecs",
            name="output_current_max_uf",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="electricalspecs",
            name="power_output_max_uf",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="electricalspecs",
            name="power_output_nominal_uf",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="electricalspecs",
            name="voltage_range_uf",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
