# Generated by Django 5.2.1 on 2025-08-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0009_apikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyMeterSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_configuration", models.IntegerField(blank=True, null=True)),
                ("frequency", models.IntegerField(blank=True, null=True)),
                ("voltage_nominal", models.IntegerField(blank=True, null=True)),
                ("voltage_tolerance_df", models.FloatField(blank=True, null=True)),
                ("current_nominal_df", models.FloatField(blank=True, null=True)),
                ("current_min_df", models.FloatField(blank=True, null=True)),
                ("current_max_df", models.FloatField(blank=True, null=True)),
                ("standby_power_consumption", models.FloatField(blank=True, null=True)),
                (
                    "power_consumption_nominal_df",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "accuracy_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_specs",
                        to="devices.asset",
                    ),
                ),
                (
                    "power_consumption_units",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.units",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InverterSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.TextField(blank=True, null=True)),
                ("phase_configuration", models.IntegerField(blank=True, null=True)),
                ("frequency", models.IntegerField(blank=True, null=True)),
                ("standby_power_consumption", models.FloatField(blank=True, null=True)),
                ("voltage_ac_l1_nom", models.FloatField(blank=True, null=True)),
                ("voltage_ac_l2_nom", models.FloatField(blank=True, null=True)),
                ("voltage_ac_l3_nom", models.FloatField(blank=True, null=True)),
                ("current_ac_l1_nom", models.FloatField(blank=True, null=True)),
                ("current_ac_l2_nom", models.FloatField(blank=True, null=True)),
                ("current_ac_l3_nom", models.FloatField(blank=True, null=True)),
                ("voltage_dc_nom", models.FloatField(blank=True, null=True)),
                ("current_dc_nom", models.FloatField(blank=True, null=True)),
                ("power_factor", models.FloatField(blank=True, null=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inverter_specs",
                        to="devices.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PVModuleSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application", models.TextField(blank=True, null=True)),
                ("module_type", models.TextField(blank=True, null=True)),
                ("module_name", models.TextField(blank=True, null=True)),
                ("voc", models.FloatField(blank=True, null=True)),
                ("isc", models.FloatField(blank=True, null=True)),
                ("vmpp", models.FloatField(blank=True, null=True)),
                ("impp", models.FloatField(blank=True, null=True)),
                ("temp_coef_pmax", models.FloatField(blank=True, null=True)),
                ("temp_coef_voc", models.FloatField(blank=True, null=True)),
                ("temp_coef_isc", models.FloatField(blank=True, null=True)),
                ("noct", models.FloatField(blank=True, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pv_module_specs",
                        to="devices.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SCCSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.TextField(blank=True, null=True)),
                ("voltage_input", models.FloatField(blank=True, null=True)),
                ("current_input", models.FloatField(blank=True, null=True)),
                ("voltage_output", models.FloatField(blank=True, null=True)),
                ("current_output", models.FloatField(blank=True, null=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scc_specs",
                        to="devices.asset",
                    ),
                ),
            ],
        ),
    ]
