# Generated by Django 5.2.1 on 2025-08-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0010_energymeterspecs_inverterspecs_pvmodulespecs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inverterspecs",
            name="current_dc_nom",
        ),
        migrations.RemoveField(
            model_name="inverterspecs",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="inverterspecs",
            name="voltage_dc_nom",
        ),
        migrations.AddField(
            model_name="inverterspecs",
            name="max_apparent_feed_in_power_kva",
            field=models.IntegerField(
                default=0, verbose_name="Maximum apparent feed-in power (kVA)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inverterspecs",
            name="max_nominal_dc_current_a",
            field=models.FloatField(
                default=0, verbose_name="Max nominal DC current (A)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inverterspecs",
            name="nom_dc_voltage_range",
            field=models.JSONField(default=dict, verbose_name="Nom DC voltage range"),
        ),
        migrations.AddField(
            model_name="inverterspecs",
            name="nominal_active_power_kw",
            field=models.IntegerField(
                default=0, verbose_name="Nominal active power (kW)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inverterspecs",
            name="peak_active_power_kw",
            field=models.IntegerField(default=0, verbose_name="Peak active power (kW)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="current_ac_l1_nom",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nominal AC Current L1 (A)"
            ),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="current_ac_l2_nom",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nominal AC Current L2 (A)"
            ),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="current_ac_l3_nom",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nominal AC Current L3 (A)"
            ),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="frequency",
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="phase_configuration",
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="voltage_ac_l1_nom",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nominal AC Voltage L1 (V)"
            ),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="voltage_ac_l2_nom",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nominal AC Voltage L2 (V)"
            ),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="voltage_ac_l3_nom",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nominal AC Voltage L3 (V)"
            ),
        ),
    ]
