# Generated by Django 5.2.1 on 2025-08-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0012_rename_inverter_ac_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inverterspecs",
            name="frequency",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="max_apparent_feed_in_power_kva",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="max_nominal_dc_current_a",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="nom_dc_voltage_range",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="nominal_ac_current_l1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="nominal_ac_current_l2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="nominal_ac_current_l3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="nominal_ac_voltage_l1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="nominal_ac_voltage_l2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="nominal_ac_voltage_l3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="nominal_active_power_kw",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="peak_active_power_kw",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="phase_configuration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="power_factor",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inverterspecs",
            name="standby_power_consumption",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
