# Generated by Django 5.1.3 on 2025-08-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0013_alter_inverterspecs_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="modbus_register_map",
            field=models.JSONField(
                blank=True,
                help_text="Crucial device/classification-specific Modbus registers (telemetry & controls).",
                null=True,
            ),
        ),
    ]
