# Generated by Django 5.2.1 on 2025-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0014_asset_modbus_register_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="dpp_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
