# Generated by Django 5.2.1 on 2025-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0015_asset_dpp_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcontributor",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="The Economic Operator's legal name (optional).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="contentcontributor",
            name="website",
            field=models.URLField(
                blank=True, help_text="The Economic Operator's website (optional)."
            ),
        ),
    ]
