# Generated by Django 5.2.1 on 2025-09-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0016_contentcontributor_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcontributor",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="contentcontributor",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
    ]
