# Generated by Django 5.2.1 on 2025-09-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0019_apikey_key_hash_apikey_last_used_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=256)),
                ("status_code", models.IntegerField()),
                ("latency_ms", models.IntegerField()),
                ("is_qr_flow", models.BooleanField(default=False)),
                ("asset_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ts"], name="devices_api_ts_0511d5_idx"),
                    models.Index(
                        fields=["is_qr_flow", "ts"],
                        name="devices_api_is_qr_f_3f50c4_idx",
                    ),
                    models.Index(
                        fields=["path", "ts"], name="devices_api_path_f76e0e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("rid", models.CharField(max_length=36, unique=True)),
                ("asset_id", models.IntegerField()),
                (
                    "qr_type",
                    models.CharField(
                        choices=[("OT", "OT"), ("DPP", "DPP")],
                        default="OT",
                        max_length=3,
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=32)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("ack", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ts"], name="devices_sca_ts_a6c45c_idx"),
                    models.Index(
                        fields=["qr_type", "ts"], name="devices_sca_qr_type_f57dc9_idx"
                    ),
                ],
            },
        ),
    ]
