# Generated by Django 5.2.1 on 2025-11-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0020_apirequestlog_scansession"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="eprel_url",
            field=models.TextField(blank=True, null=True, verbose_name="EPREL URL"),
        ),
        migrations.AddField(
            model_name="asset",
            name="vendor",
            field=models.TextField(blank=True, null=True, verbose_name="Vendor"),
        ),
        migrations.AddField(
            model_name="electricalspecs",
            name="energy_class",
            field=models.TextField(blank=True, null=True, verbose_name="Energy Class"),
        ),
    ]
